#!/bin/bash 

REPO_DIR="${HOME}/.stdst8"
cat ${REPO_DIR}/stdst8-logo 

cd ${REPO_DIR}/ && git pull

# Sourcing the lib
# shellcheck source=lib/stdst8-functions.sh
source "${REPO_DIR}/lib/stdst8-functions.sh"

echo "Updating stdst8 tooling"

stdst8.update_terraform

echo "Update complete"
