#!/bin/bash

# The install script takes care of the following : 
# - Set up the proper files and folders to store config and tools
#   - Local bin              ~/.local/bin
#   - Local config           ~/.config/stdst8
#   - Local source code      ~/Src 
# - Clone the source repo in ~/.stdst8
# - Set up the update trigger in the ~/.zshrc file

# -e  Exit immediately if a command exits with a non-zero status.
set -e

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1 

# Litlle bit of ascii art from http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Fraktur&t=stdst8
cat ${_SCRIPT_DIR}/stdst8-logo                                                                                                                  

# Sourcing the vars
# shellcheck source=lib/stdst8-variables.sh
source "${_SCRIPT_DIR}/lib/stdst8-variables.sh"

# Sourcing the lib
# shellcheck source=lib/stdst8-functions.sh
source "${_SCRIPT_DIR}/lib/stdst8-install.sh"

# Local bin folder
stdst8.install_local_bin_folder

# Local config folder
stdst8.install_local_config_folder

# Local source dir
stdst8.install_local_source_folder

# Clone the repo to ~/.stdst8
stdst8.clone_repo

# Installing the update file
stdst8.install_update_script

## Trigger the update
#echo "Restarting ${SHELL} to trigger the update"
#exec ${SHELL}
#
## This line will never be printed !!!
#echo "Spaceballs - the script"
