#!/bin/bash

# -e  Exit immediately if a command exits with a non-zero status.
set -e

# This installs the necessary scripts, configs and folders to then run the update script.

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1 
echo "Script directory : ${_SCRIPT_DIR}"

# Display logo
# Litlle bit of ascii art from http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Fraktur&t=stdst8
cat ${_SCRIPT_DIR}/stdst8-logo                                                                                                                  

# Installation
echo "Installing the stdst8 tooling on this workstation"

# Sourcing the lib
# shellcheck source=lib/stdst8-functions.sh
source "${_SCRIPT_DIR}/lib/stdst8-functions.sh"

# Local bin folder
echo "Validating the local bin folder, creating if required"
stdst8.install_local_bin_folder
echo

# Clone the repo to ~/.stdst8
echo "Cloning stdst8 tooling repo"
stdst8.clone_repo

# Installing the update file
echo "Setting automatic updates on shell startup in rc file"
stdst8.install_update_script
echo

# Trigger the update
echo "Restarting ${SHELL} to trigger the update"
exec ${SHELL}

# This line will never be printed !!!
echo "Spaceballs - the script"
