#!/bin/bash

# The update script takes care of the following : 
#   - Go
#   - Vim updates and tooling
#   - Brave browser
#   - AWS cli and tooling
 

# -e  Exit immediately if a command exits with a non-zero status.
set -e

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1 

# Litlle bit of ascii art from http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Fraktur&t=stdst8
cat ${_SCRIPT_DIR}/stdst8-logo                                                                                                                  

# Sourcing the vars
# shellcheck source=lib/stdst8-variables.sh
source "${_SCRIPT_DIR}/lib/stdst8-variables.sh"

# Sourcing the lib for the go installation
# shellcheck source=lib/stdst8-go.sh
source "${_SCRIPT_DIR}/lib/stdst8-go.sh"

# Sourcing the lib for the go installation
# shellcheck source=lib/stdst8-vim.sh
source "${_SCRIPT_DIR}/lib/stdst8-vim.sh"

# Sourcing the lib for the go installation
# shellcheck source=lib/stdst8-brave.sh
source "${_SCRIPT_DIR}/lib/stdst8-brave.sh"

# Sourcing the lib for the terraform installation
# shellcheck source=lib/stdst8-terraform.sh
source "${_SCRIPT_DIR}/lib/stdst8-terraform.sh"

# Sourcing the lib for the aws installation
# shellcheck source=lib/stdst8-aws.sh
source "${_SCRIPT_DIR}/lib/stdst8-aws.sh"

# Installing Go
stdst8.update_go

# Installing Vim and related tooling
stdst8.install_vim_and_tooling

# Installing Brave browser
stdst8.install_brave_browser

# Installing AWS cli and tooling
stdst8.install_aws_tooling



